version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  slack: circleci/slack@4.1.3
jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}
  deploy-to-aws-s3:
    docker:
    - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
  deploy-to-cloudfront:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          context:
            - AWS_ACCESS_KEY
            - SLACK
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develop
                - staging
                - master